# Puerto estandar del servidor de configuracion
server.port=8888

# Nombre de la aplicacion
spring.application.name=config-server

# Usar el sistema de archivos local (classpath)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations