# Puerto estandar de Eureka
server.port=8761

# Nombre del servicio
spring.application.name=eureka-server

# Deshabilitar que Eureka intente registrarse a si mismo
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/