spring.application.name=banco-service

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:h2:mem:bankdb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

spring.activemq.broker-url=tcp://localhost:61616

spring.activemq.user=admin

spring.activemq.password=admin

# resilience4j circuit breaker

resilience4j.circuitbreaker.instances.envioJms.slidingWindowType=COUNT_BASED

resilience4j.circuitbreaker.instances.envioJms.slidingWindowSize=5

resilience4j.circuitbreaker.instances.envioJms.minimumNumberOfCalls=3

resilience4j.circuitbreaker.instances.envioJms.failureRateThreshold=50

resilience4j.circuitbreaker.instances.envioJms.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.envioJms.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.envioJms.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.envioJms.registerHealthIndicator=true